name: Run CI

on:
  workflow_dispatch:
    inputs:
      project:
        description: Playwright project
        default: replay-firefox
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true

      - name: Install Replay Playwright Browsers
        run: npx @replayio/playwright install

      - name: Test and Upload
        uses: replayio/action-playwright@v0.4.12
        with:
          project: ${{ github.event.inputs.project || 'replay-firefox' }}
          apiKey: ${{ secrets.RECORD_REPLAY_API_KEY }}
          issue-number: ${{ github.event.pull_request.number }}
          public: true
          upload-all: true
