name: Test Upload action

on:
  workflow_dispatch:
    inputs:
      cli-version:
        description: "CLI Version"
        default: latest

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Test
        run: npx playwright test --project replay-firefox
        shell: sh
        
      - name: debug
        uses: actions/github-script@v6
        with:
          result-encoding: json
          script: |
            console.log(JSON.stringify(context, undefined, 2));
            console.log("repo", process.env.GITHUB_REPOSITORY);

      - name: Test and Upload
        uses: replayio/action-upload@ryan/add-trigger-url
        with:
          cli-version: ${{ github.event.inputs.cli-version }}
          apiKey: ${{ secrets.RECORD_REPLAY_API_KEY }}
