name: Test Upload action

on:
  workflow_dispatch:
    inputs:
      cli-version:
        description: "CLI Version"
        default: latest

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test and Upload
        uses: replayio/action-upload@ryan-dynamic-import
        with:
          apiKey: ${{ secrets.RECORD_REPLAY_API_KEY }}
          cli-version: ${{ github.event.inputs.cli-version }}
